# Generated by Django 4.1.6 on 2023-05-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe_Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Recipe_Name', models.CharField(max_length=50)),
                ('Ingrediants', models.CharField(max_length=300)),
                ('Meal_Type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=20)),
                ('Health_type', models.CharField(max_length=40)),
                ('Diet', models.CharField(choices=[('balanced', 'Balanced'), ('high-fiber', 'High-Fiber'), ('high-protein', 'High-Protein'), ('low-carb', 'Low-Carb'), ('low-fat', 'Low-Fat'), ('low-sodium', 'Low-Sodium')], max_length=40)),
                ('Calories', models.IntegerField()),
                ('Time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('like_recipe', models.URLField()),
                ('experience', models.CharField(max_length=500)),
                ('calories_count', models.IntegerField()),
            ],
        ),
    ]
