# Generated by Django 4.1.6 on 2023-05-10 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Create_RecipeName', models.CharField(max_length=50)),
                ('Create_Ingrediants', models.CharField(max_length=300)),
                ('Create_Meal_Type', models.CharField(choices=[('', 'None'), ('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=20)),
                ('Create_Health_Type', models.CharField(choices=[('', 'None'), ('alcohol-cocktail', 'Alcohol-Cocktail'), ('alcohol-free', 'Alcohol-Free'), ('celery-free', 'Celery-Free'), ('crustacean-free', 'Crustacean-Free'), ('dairy-free', 'Dairy-Free'), ('dash', 'DASH'), ('egg-free', 'Egg-Free'), ('fish-free', 'Fish-Free'), ('foodmap-free', 'Foodmap-Free'), ('gluten-free', 'Gluten-Free'), ('immuno-supportive', 'Immuno-Supportive'), ('keto-friendly', 'Keto-Friendly'), ('kidney-friendly', 'Kidney-Friendly'), ('kosher', 'Kosher'), ('low-fat-abs', 'Low-Fat-Abs'), ('low-potassium', 'Low-Potassium'), ('low-sugar', 'Low-Sugar'), ('lupine-free', 'Lupine-Free'), ('mediterranean', 'Mediterranean'), ('mollusk-free', 'Mollusk-Free'), ('mustard-free', 'Mustard-Free'), ('no-oil-added', 'No-Oil-Added'), ('paleo', 'Paleo'), ('peanut-free', 'Peanut-Free'), ('pescatarian', 'Pescatarian'), ('pork-free', 'Pork-Free'), ('red-meat-free', 'Red-Meat-Free'), ('sesame-free', 'Sesame-Free'), ('shellfish-free', 'Shellfish-Free'), ('soy-free', 'Soy-Free'), ('sugar-conscious', 'Sugar-Concious'), ('sulfite-free', 'Sulfite-Free'), ('tree-nut-free', 'Tree-Nut-Free'), ('vegan', 'Vegan'), ('vegetarian', 'Vegetarian'), ('wheat-free', 'Wheat-Free')], max_length=40)),
                ('Create_Diet', models.CharField(choices=[('', 'None'), ('balanced', 'Balanced'), ('high-fiber', 'High-Fiber'), ('high-protein', 'High-Protein'), ('low-carb', 'Low-Carb'), ('low-fat', 'Low-Fat'), ('low-sodium', 'Low-Sodium')], max_length=40)),
                ('Create_Calories', models.CharField(max_length=50)),
                ('Create_Time', models.CharField(max_length=50)),
                ('Create_Instruct', models.CharField(default='', max_length=10000)),
                ('Upload_Image', models.ImageField(blank=True, null=True, upload_to='Uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Recipe_Name', models.CharField(max_length=50)),
                ('Ingrediants', models.CharField(max_length=300, null=True)),
                ('Meal_Type', models.CharField(choices=[('', 'None'), ('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=20, null=True)),
                ('Health_Type', models.CharField(choices=[('', 'None'), ('alcohol-cocktail', 'Alcohol-Cocktail'), ('alcohol-free', 'Alcohol-Free'), ('celery-free', 'Celery-Free'), ('crustacean-free', 'Crustacean-Free'), ('dairy-free', 'Dairy-Free'), ('dash', 'DASH'), ('egg-free', 'Egg-Free'), ('fish-free', 'Fish-Free'), ('foodmap-free', 'Foodmap-Free'), ('gluten-free', 'Gluten-Free'), ('immuno-supportive', 'Immuno-Supportive'), ('keto-friendly', 'Keto-Friendly'), ('kidney-friendly', 'Kidney-Friendly'), ('kosher', 'Kosher'), ('low-fat-abs', 'Low-Fat-Abs'), ('low-potassium', 'Low-Potassium'), ('low-sugar', 'Low-Sugar'), ('lupine-free', 'Lupine-Free'), ('mediterranean', 'Mediterranean'), ('mollusk-free', 'Mollusk-Free'), ('mustard-free', 'Mustard-Free'), ('no-oil-added', 'No-Oil-Added'), ('paleo', 'Paleo'), ('peanut-free', 'Peanut-Free'), ('pescatarian', 'Pescatarian'), ('pork-free', 'Pork-Free'), ('red-meat-free', 'Red-Meat-Free'), ('sesame-free', 'Sesame-Free'), ('shellfish-free', 'Shellfish-Free'), ('soy-free', 'Soy-Free'), ('sugar-conscious', 'Sugar-Concious'), ('sulfite-free', 'Sulfite-Free'), ('tree-nut-free', 'Tree-Nut-Free'), ('vegan', 'Vegan'), ('vegetarian', 'Vegetarian'), ('wheat-free', 'Wheat-Free')], max_length=40, null=True)),
                ('Diet', models.CharField(choices=[('', 'None'), ('balanced', 'Balanced'), ('high-fiber', 'High-Fiber'), ('high-protein', 'High-Protein'), ('low-carb', 'Low-Carb'), ('low-fat', 'Low-Fat'), ('low-sodium', 'Low-Sodium')], max_length=40, null=True)),
                ('Calories', models.CharField(max_length=50, null=True)),
                ('Time', models.IntegerField(null=True)),
                ('shareable_link', models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecomendedRecipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rec_Recipe_Name', models.CharField(max_length=50)),
                ('Rec_URL', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('follows', models.ManyToManyField(blank=True, related_name='followed_by', to='API.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
