# Generated by Django 4.1.6 on 2023-05-14 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createrecipe',
            name='Create_RecipeCount',
            field=models.IntegerField(null=True),
        ),
    ]
