# Generated by Django 4.1.6 on 2023-05-03 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(),
        ),
    ]
