# Generated by Django 4.1.6 on 2023-05-03 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
