# Generated by Django 4.1.6 on 2023-05-03 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_remove_profile_image_profile_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_pic',
            new_name='pic',
        ),
    ]
