# Generated by Django 4.1.6 on 2023-05-03 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_rename_profile_pic_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='pic',
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
